# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request,
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        echo git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git checkout test
        echo git pull github ${GITHUB_REF} --ff-only
        git pull github ${GITHUB_REF} --ff-only
        echo git merge origin/master
        git merge origin/master --no-ff
        echo git push github HEAD:${GITHUB_REF}
        git push github HEAD:${GITHUB_REF}
 
